package com.example.motivational.qoutes.utils

import com.example.motivational.qoutes.R
import com.example.motivational.qoutes.database.QuotModel
import java.util.Random

object UtilLists {

    val catWallpapers = intArrayOf(
        R.drawable.cat0,
        R.drawable.cat1,
        R.drawable.cat2,
        R.drawable.cat3,
        R.drawable.cat4,
        R.drawable.cat5,
        R.drawable.cat6,
        R.drawable.cat7,
        R.drawable.cat8,
        R.drawable.cat9,
        R.drawable.cat10,
        R.drawable.cat11,
        R.drawable.cat12,
        R.drawable.cat13,
        R.drawable.cat14,
        R.drawable.cat15,
        R.drawable.cat16,
        R.drawable.cat18,
        R.drawable.cat19,
        R.drawable.cat20,
        R.drawable.cat22,
        R.drawable.cat23,
        R.drawable.cat24,
        R.drawable.cat25,
        R.drawable.cat26,
        R.drawable.cat27,
        R.drawable.cat28,
        R.drawable.cat29,
        R.drawable.cat30,
        R.drawable.cat31
    )
    val cats = arrayOf(
        "life",
        "happiness",
        "love",
        "truth",
        "inspiration",
        "humor",
        "philosophy",
        "science",
        "soul",
        "books",
        "wisdom",
        "knowledge",
        "education",
        "poetry",
        "hope",
        "friendship",
        "writing",
        "death",
        "romance",
        "success",
        "arts",
        "relationship",
        "motivation",
        "faith",
        "mind",
        "god",
        "funny",
        "quotes",
        "positive",
        "purpose"
    )
    val wallpapers = intArrayOf(
        R.drawable.rp8,
        R.drawable.rp1,
        R.drawable.rp2,
        R.drawable.rp3,
        R.drawable.rp4,
        R.drawable.rp5,
        R.drawable.rp36,
        R.drawable.rp6,
        R.drawable.rp7,
        R.drawable.rp35,
        R.drawable.rp9,
        R.drawable.rp10,
        R.drawable.rp11,
        R.drawable.rp12,
        R.drawable.rp13,
        R.drawable.rp14,
        R.drawable.rp15,
        R.drawable.rp16,
        R.drawable.rp17,
        R.drawable.rp39,
        R.drawable.rp18,
        R.drawable.rp19,
        R.drawable.rp20,
        R.drawable.rp21,
        R.drawable.rp22,
        R.drawable.rp23,
        R.drawable.rp37,
        R.drawable.rp24,
        R.drawable.rp25,
        R.drawable.rp26,
        R.drawable.rp27,
        R.drawable.rp28,
        R.drawable.rp29,
        R.drawable.rp30,
        R.drawable.rp31,
        R.drawable.rp38,
        R.drawable.rp32,
        R.drawable.rp32,
        R.drawable.rp34
    )
    val quoteSplash= arrayOf(
        "“Either you run the day or the day runs you.” — Jim Rohn",
        "“Don’t let yesterday take up too much of today.” — Will Rogers",
        "“He who conquers himself is the mightiest warrior.” — Confucius",
        "“One man with courage makes a majority.” – Andrew Jackson",
        "“Opportunities don't happen, you create them.” — Chris Grosser",
        "“If you can dream it, you can do it.” ―Walt Disney"
    )
    val wallSplash= intArrayOf(
        R.drawable.sp1,
        R.drawable.sp2,
        R.drawable.sp3,
        R.drawable.sp4,
        R.drawable.sp5,
        R.drawable.sp6
    )
}